# Generated by Django 5.1.15 on 2026-07-15 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Raffle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RaffleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eliminated_order",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("eliminated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "raffle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="raffle.raffle",
                    ),
                ),
            ],
            options={
                "ordering": ["player__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raffle", "player"), name="uniq_raffle_player"
                    ),
                    models.UniqueConstraint(
                        fields=("raffle", "eliminated_order"),
                        name="uniq_raffle_elim_order",
                    ),
                ],
            },
        ),
    ]
