# Generated by Django 5.1.15 on 2026-07-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raffle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
