# Generated by Django 5.1.15 on 2026-06-01 18:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_role_split_and_org_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.avatar_upload_to
            ),
        ),
    ]
