# Generated by Django 5.1.11 on 2026-06-05 11:44

from django.db import migrations, models


def forwards_move_sie_sede_to_dept(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(sede="sie", dept="").update(dept="sie")
    User.objects.filter(sede="sie").update(sede="")


def reverse_move_sie_dept_to_sede(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(dept="sie", sede="").update(sede="sie", dept="")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_update_org_choices"),
    ]

    operations = [
        migrations.RunPython(forwards_move_sie_sede_to_dept, reverse_move_sie_dept_to_sede),
        migrations.AlterField(
            model_name="user",
            name="dept",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gestion", "Gestión"),
                    ("financiera", "Financiera"),
                    ("nominas", "Nóminas"),
                    ("entorno", "Entorno"),
                    ("galileo", "Servicios Galileo"),
                    ("web_movilidad", "Web y Movilidad"),
                    ("pesca", "Pesca"),
                    ("aluminio", "Aluminio"),
                    ("farmacia", "Farmacia"),
                    ("sistemas", "Sistemas"),
                    ("sie", "SIE"),
                    ("atencion_clientes", "Atención clientes"),
                    ("otros", "Otros"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sede",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ourense", "Ourense"),
                    ("vigo", "Vigo"),
                    ("asturias", "Asturias"),
                    ("madrid", "Madrid"),
                    ("barcelona", "Barcelona"),
                ],
                max_length=20,
            ),
        ),
    ]
