# Generated by Django 5.1.15 on 2026-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=80)),
                ("flag", models.CharField(max_length=8)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
