# Generated by Django 5.1.15 on 2026-05-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=40)),
                ("short", models.CharField(max_length=10)),
                ("points", models.PositiveSmallIntegerField()),
                ("order", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
