# Generated by Django 5.1.15 on 2026-05-31 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=20)),
                ("matchday", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("kickoff", models.DateTimeField()),
                (
                    "result_home",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "result_away",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "away",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="away_matches",
                        to="competition.team",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="home_matches",
                        to="competition.team",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="competition.round",
                    ),
                ),
            ],
            options={
                "ordering": ["kickoff"],
                "indexes": [
                    models.Index(
                        fields=["round", "matchday", "kickoff"],
                        name="competition_round_i_dc6529_idx",
                    ),
                    models.Index(
                        fields=["finished_at"], name="competition_finishe_5a0220_idx"
                    ),
                ],
            },
        ),
    ]
