# Generated by Django 5.1.11 on 2026-06-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0004_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetsClosingReport",
            fields=[
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="closing_report",
                        serialize=False,
                        to="competition.match",
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at"], name="competition_sent_at_d94eeb_idx"
                    )
                ],
            },
        ),
    ]
