# Generated by Django 5.1.15 on 2026-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0005_betsclosingreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="partial_points",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
