# Generated by Django 5.1.15 on 2026-06-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0007_match_points_applied"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetsReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("T_MINUS_4H", "2 h antes del cierre"),
                            ("T_MINUS_2_5H", "30 min antes del cierre"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                ("pending_count", models.PositiveSmallIntegerField()),
                ("pending_names", models.JSONField(default=list)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="competition.match",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at"], name="competition_sent_at_cc8b68_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "kind"), name="uniq_reminder_per_match_kind"
                    )
                ],
            },
        ),
    ]
