# Generated by Django 5.1.15 on 2026-06-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0008_betsreminderlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_slot",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="match",
            name="bracket_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_slot",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="match",
            name="away",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="competition.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="competition.team",
            ),
        ),
    ]
