# Generated by Django 5.1.15 on 2026-06-10 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0010_rename_reminder_kinds"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="external_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="LiveScore",
            fields=[
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="live_score",
                        serialize=False,
                        to="competition.match",
                    ),
                ),
                ("home_score", models.PositiveSmallIntegerField(default=0)),
                ("away_score", models.PositiveSmallIntegerField(default=0)),
                ("minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("PRE", "Antes del saque"),
                            ("1H", "1ª parte"),
                            ("HT", "Descanso"),
                            ("2H", "2ª parte"),
                            ("ET", "Prórroga"),
                            ("PEN", "Penaltis"),
                            ("FT", "Final"),
                        ],
                        default="PRE",
                        max_length=4,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["updated_at"], name="competition_updated_f908c0_idx"
                    )
                ],
            },
        ),
    ]
