# Generated by Django 5.1.15 on 2026-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0011_live_score_and_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="bracket_order",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
