# Generated by Django 5.1.15 on 2026-06-03 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competition", "0007_match_points_applied"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WinnerAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_kind",
                    models.CharField(
                        choices=[
                            ("matchday", "Jornada de grupos"),
                            ("round", "Ronda KO"),
                            ("global", "Campeón del Mundial"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "scope_matchday",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("points", models.PositiveIntegerField()),
                ("tied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope_round",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="announcements",
                        to="competition.round",
                    ),
                ),
                (
                    "winners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="winning_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WinnerAnnouncementSeen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_by",
                        to="announcements.winnerannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seen_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="winnerannouncement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_kind", "matchday")),
                fields=("scope_kind", "scope_matchday"),
                name="uniq_ann_matchday",
            ),
        ),
        migrations.AddConstraint(
            model_name="winnerannouncement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_kind", "round")),
                fields=("scope_kind", "scope_round"),
                name="uniq_ann_round",
            ),
        ),
        migrations.AddConstraint(
            model_name="winnerannouncement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_kind", "global")),
                fields=("scope_kind",),
                name="uniq_ann_global",
            ),
        ),
        migrations.AddIndex(
            model_name="winnerannouncementseen",
            index=models.Index(
                fields=["user", "announcement"], name="announcemen_user_id_324cb6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="winnerannouncementseen",
            constraint=models.UniqueConstraint(
                fields=("announcement", "user"), name="uniq_seen_per_user"
            ),
        ),
    ]
