# Generated by Django 5.1.11 on 2026-06-05 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0002_winnerannouncement_share"),
        ("competition", "0009_match_slots_and_nullable_teams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="winnerannouncement",
            name="scope_kind",
            field=models.CharField(
                choices=[
                    ("matchday", "Jornada de grupos"),
                    ("round", "Ronda KO"),
                    ("global", "Campeón del Mundial"),
                    ("sede", "Ganadores por sede"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="winnerannouncement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_kind", "sede")),
                fields=("scope_kind",),
                name="uniq_ann_sede",
            ),
        ),
    ]
