# Generated by Django 5.1.11 on 2026-06-05 16:39

from django.conf import settings
from django.db import migrations, models


def delete_round_announcements(apps, schema_editor):
    WinnerAnnouncement = apps.get_model("announcements", "WinnerAnnouncement")
    WinnerAnnouncement.objects.filter(scope_kind="round").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0003_winnerannouncement_sede_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_round_announcements, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="winnerannouncement",
            name="uniq_ann_round",
        ),
        migrations.RemoveField(
            model_name="winnerannouncement",
            name="scope_round",
        ),
        migrations.AlterField(
            model_name="winnerannouncement",
            name="scope_kind",
            field=models.CharField(
                choices=[
                    ("matchday", "Jornada de grupos"),
                    ("ko", "Jornada eliminatoria"),
                    ("global", "Campeón del Mundial"),
                    ("sede", "Ganadores por sede"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="winnerannouncement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope_kind", "ko")),
                fields=("scope_kind",),
                name="uniq_ann_ko",
            ),
        ),
    ]
