# Generated by Django 5.1.15 on 2026-05-31 12:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "per_player",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=8
                    ),
                ),
                ("allowed_email_domains", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Pot settings",
            },
        ),
    ]
