# Generated by Django 5.1.15 on 2026-05-31 12:35

from decimal import Decimal

from django.db import migrations


def seed_prizes(apps, schema_editor):
    Prize = apps.get_model("pot", "Prize")
    PotSettings = apps.get_model("pot", "PotSettings")

    PotSettings.objects.get_or_create(pk=1, defaults={"per_player": Decimal("10.00")})

    for pos, label in [(1, "1er premio"), (2, "2º premio"), (3, "3er premio")]:
        Prize.objects.get_or_create(
            scope="global", position=pos, defaults={"amount": 0, "label": label}
        )


def reverse_seed(apps, schema_editor):
    apps.get_model("pot", "Prize").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pot", "0002_payment_prize"),
        ("competition", "0002_round"),
    ]
    operations = [migrations.RunPython(seed_prizes, reverse_seed)]
