# Generated by Django 5.1.15 on 2026-05-31 12:35

from django.db import migrations
from decimal import Decimal


def seed_prizes(apps, schema_editor):
    Round = apps.get_model("competition", "Round")
    Prize = apps.get_model("pot", "Prize")
    PotSettings = apps.get_model("pot", "PotSettings")

    PotSettings.objects.get_or_create(pk=1, defaults={"per_player": Decimal("10.00")})

    for pos, label in [(1, "1er premio"), (2, "2º premio"), (3, "3er premio")]:
        Prize.objects.get_or_create(scope="global", position=pos,
                                     defaults={"amount": 0, "label": label})
    for md in (1, 2, 3):
        Prize.objects.get_or_create(scope="matchday", matchday=md,
                                     defaults={"amount": 0, "label": f"Jornada {md} (Grupos)"})
    for rid, label in [("r32", "Dieciseisavos"), ("r16", "Octavos"), ("qf", "Cuartos")]:
        try:
            r = Round.objects.get(pk=rid)
        except Round.DoesNotExist:
            continue
        Prize.objects.get_or_create(scope="round", round=r,
                                     defaults={"amount": 0, "label": f"Ronda · {label}"})


def reverse_seed(apps, schema_editor):
    apps.get_model("pot", "Prize").objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pot", "0002_payment_prize"),
        ("competition", "0002_round"),
    ]
    operations = [migrations.RunPython(seed_prizes, reverse_seed)]
