# Generated by Django 5.1.11 on 2026-06-02 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pot", "0003_seed_prizes"),
    ]

    operations = [
        migrations.AddField(
            model_name="potsettings",
            name="matchday_winner_prize",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
    ]
