# Generated by Django 5.1.11 on 2026-06-05 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pot", "0006_potsettings_maintenance_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="potsettings",
            name="sede_winner_prize",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
    ]
